language: go

go_import_path: go-dart

go:
  - 1.6

before_install:
  - yes | sudo add-apt-repository ppa:masterminds/glide && sudo apt-get update
  - sudo apt-get install glide
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/mattn/goveralls

install:
  - glide install

script:
  - go test -v $(glide novendor)
  - go test -v -covermode=count -coverprofile=coverage.out ./server/

after_success:
  - goveralls -coverprofile=coverage.out -service=travis-ci
